# Generated by Django 4.2.14 on 2024-08-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameachievement',
            name='app_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
