# Generated by Django 4.2.14 on 2024-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_gameachievement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameachievement',
            name='user_steam_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
