# Generated by Django 4.2.14 on 2024-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_gameachievement_user_steam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameachievement',
            name='game_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
