# Generated by Django 4.2.14 on 2024-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id_user', models.CharField(max_length=50, null=True)),
                ('friends_list', models.JSONField()),
            ],
        ),
    ]
