# Generated by Django 4.2.14 on 2024-08-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriends',
            name='steam_id_user',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
