# Generated by Django 4.2.14 on 2024-08-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_userfriends_steam_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriends',
            name='friends_info',
            field=models.JSONField(null=True),
        ),
    ]
