# Generated by Django 4.2.14 on 2024-08-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_userfriends_friends_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfriends',
            name='friends_list',
        ),
    ]
