# Generated by Django 4.2.14 on 2024-08-20 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=730)),
                ('total_kills', models.IntegerField(null=True)),
                ('total_deaths', models.IntegerField(null=True)),
                ('total_time_played', models.IntegerField(null=True)),
                ('total_planted_bombs', models.IntegerField(null=True)),
                ('total_defused_bombs', models.IntegerField(null=True)),
                ('total_wins', models.IntegerField(null=True)),
                ('total_damage_done', models.IntegerField(null=True)),
                ('total_money_earned', models.IntegerField(null=True)),
                ('total_wins_pistolround', models.IntegerField(null=True)),
                ('total_mvps', models.IntegerField(null=True)),
                ('total_matches_won', models.IntegerField(null=True)),
                ('total_matches_played', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
