# Generated by Django 4.2.14 on 2024-08-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic_from_user', '0002_gamestats_delete_gamestatsuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='user',
        ),
        migrations.AddField(
            model_name='gamestats',
            name='user_steam_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
