# Generated by Django 4.2.14 on 2024-08-17 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSteam',
            fields=[
                ('app_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url_image', models.URLField()),
                ('genre', models.TextField()),
                ('release_date', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('players_in_game', models.CharField(default='Нет информации')),
                ('last_update', models.CharField(default=datetime.datetime(2024, 8, 17, 22, 29, 1, 24408, tzinfo=datetime.timezone.utc))),
                ('minutes_update', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'GameSteam',
            },
        ),
    ]
