# Generated by Django 4.2.14 on 2024-08-18 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesteam',
            name='last_update',
            field=models.CharField(default=datetime.datetime(2024, 8, 18, 10, 16, 16, 838108, tzinfo=datetime.timezone.utc)),
        ),
    ]
