# Generated by Django 4.2.14 on 2024-08-22 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_gamesteam_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesteam',
            name='last_update',
        ),
        migrations.AddField(
            model_name='gamesteam',
            name='last_update_news',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 22, 26, 5, 862009)),
        ),
        migrations.AddField(
            model_name='gamesteam',
            name='last_update_players',
            field=models.CharField(default=datetime.datetime(2024, 8, 22, 19, 26, 5, 861967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='gamesteam',
            name='news',
            field=models.JSONField(null=True),
        ),
    ]
