# Generated by Django 4.2.14 on 2024-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='profileurl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='steam_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
