# Generated by Django 4.2.14 on 2024-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_steamuser_profileurl_alter_steamuser_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='avatarfull',
            field=models.URLField(blank=True, default='https://bootdey.com/img/Content/avatar/avatar7.png', null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='personaname',
            field=models.CharField(blank=True, default='Нет информации', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='profilestate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
