# Generated by Django 4.2.14 on 2024-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_steamuser_avatarfull_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='steam_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
