# Generated by Django 4.2.14 on 2024-08-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_steamuser_steam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='last_update',
            field=models.DateField(null=True),
        ),
    ]
