# Generated by Django 4.2.14 on 2024-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_steamuser_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecentlyPlayedGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_steam_id', models.CharField(max_length=50, null=True)),
                ('app_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('playtime_2weeks', models.IntegerField(null=True)),
                ('img_icon_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='steamuser',
            name='last_update_url',
            field=models.DateTimeField(null=True),
        ),
    ]
