# Generated by Django 4.2.14 on 2024-08-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userrecentlyplayedgames_steamuser_last_update_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentlyplayedgames',
            name='total_playtime_2weeks',
            field=models.IntegerField(null=True),
        ),
    ]
