# Generated by Django 4.2.14 on 2024-08-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userrecentlyplayedgames_total_playtime_2weeks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecentlyplayedgames',
            unique_together={('user_steam_id', 'app_id')},
        ),
    ]
