# Generated by Django 4.2.14 on 2024-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userrecentlyplayedgames_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentlyplayedgames',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
