# Generated by Django 4.2.14 on 2024-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userrecentlyplayedgames_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecentlyplayedgames',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
